export default {

    FORM_FILL:'FORM_FILL' as const,
    INFO_LIST:'INFO_LIST' as const,
    ANIMATION_SCREEN:'ANIMATION_SCREEN' as const,
    NOTIFICATION_SCREEN:'NOTIFICATION_SCREEN' as const,
    LISTER_SCREEN:'LISTER_SCREEN' as const,
    TEXT_SCREEN:'TEXT_SCREEN' as const,
    HORIZONTAL_PARALX_SCREEN:'HORIZONTAL_PARALX_SCREEN' as const,
    HEAR_BEAT_SCREEN:'HEAR_BEAT_SCREEN' as const,
    LOADING_ANIMATION_SCREEN:'LOADING_ANIMATION_SCREEN' as const,
    SWITCH_ANIMATION_SCREEN:'SWITCH_ANIMATION_SCREEN' as const,
    BOX_ANIMATION_SCREEN:'BOX_ANIMATION_SCREEN' as const,
    DOUBLE_TAP_ANIMATION_SCREEN:'DOUBLE_TAP_ANIMATION_SCREEN' as const



}